### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by haoshuai714** [epic-kitchens/epic-sounds-annotations#7]
When I directly used the pre trained model test, an error occurred:ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
Can I directly use the pre training model provided by github for direct testing?

**Comment by JacobChalk** [comment]
What command are you running to get the test results? Are you running `test_net.py` on the validation split? Or test timestamps?

**Comment by JacobChalk** [comment]
It seems likely this error is caused from running `test_net.py` on the test timestamps file, where the dataset gives all samples a fake label of 0, which breaks the evaluation code due to the error stated in this issue. We have just pushed a change to fix this. It's worth noting that metrics on the test set can only be obtained by entering and submitting to the [audio-based interaction recognition challenge](https://codalab.lisn.upsaclay.fr/competitions/9729).

**Comment by haoshuai714** [comment]
**yes， you are right.  I ran the command:**
python tools/run_net.py \
--cfg configs/EPIC-Sounds/slowfast/SLOWFASTAUDIO_8x8_R50.yaml \
TRAIN.ENABLE False \
TEST.ENABLE True \
NUM_GPUS num_gpus \
OUTPUT_DIR /path/to/outpur_dir \
EPICSOUNDS.AUDIO_DATA_FILE /path/to/EPIC_audio.hdf5 \
EPICSOUNDS.ANNOTATIONS_DIR /path/to/annotations \
TEST.CHECKPOINT_FILE_PATH /path/to/experiment_dir/checkpoints/checkpoint_best.pyth \
EPICSOUNDS.TEST_LIST EPIC_Sounds_recognition_test_timestamps.pkl

**Can I now use the pre-trained model and code you provided to run the files submitted for the competition?**

**Comment by JacobChalk** [comment]
Yes you should be able to now. The `TestMeter` has been [updated](https://github.com/epic-kitchens/epic-sounds-annotations/blob/f65cece5b0bd1610da2201e7008952240502769d/src/slowfast/utils/meters.py#L540) so that it sees if you are running inference on the test split, if you are (and assuming the file names are as they are in this repo), it will not compute stats and only extract predictions when using the test timestamp

**Comment by haoshuai714** [comment]
In other words, the pre-trained model you provided can be used directly for testing, or for fine-tune in the training phase, right?

**Comment by JacobChalk** [comment]
Yes, it can be used for both with the current code

**Comment by haoshuai714** [comment]
I run a new code library, and a new bug appears：
[03/22 02:30:59][INFO] epicsounds.py- 76: Constructing audio annotations dataloader (size: 25655) from ['/data/EPIC/audio_model/annotations/EPIC_Sounds_recognition_test_timestamps.pkl']
[03/22 02:30:59][INFO] test_net.py-142: Testing model for 201 iterations
Traceback (most recent call last):
  File "/data/EPIC/audio_model/tools/run_net.py", line 31, in <module>
    main()
  File "/data/EPIC/audio_model/tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/data/EPIC/audio_model/slowfast/utils/misc.py", line 244, in launch_job
    func(cfg=cfg)
  File "/data/EPIC/audio_model/tools/test_net.py", line 144, in test
    test_meter = TestMeter(
**TypeError: __init__() takes 5 positional arguments but 6 were given**

**Comment by haoshuai714** [comment]
After running the test code, I generated the **epic_sounds_recognition_test_timestamps.pkl** document.
However, the official website submission is a **JSON file: $ zip -j my-submission.zip test.json.**
How should I generate related **test.json**?

**Comment by JacobChalk** [comment]
The output predictions in the .pkl format can be made into the JSON submission by following the instructions on the challenge repo [here](https://github.com/epic-kitchens/C9-epic-sounds).
